# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-proto-recordproto
Summary:    X.Org X11 Protocol recordproto
Version:    1.14.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/recordproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-recordproto.yaml
Provides:   recordproto


%description
%{summary}.




%prep
%setup -q -n recordproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/recordproto.pc
%{_includedir}/X11/extensions/recordstr.h
%{_includedir}/X11/extensions/recordconst.h
%{_includedir}/X11/extensions/recordproto.h
%doc %{_datadir}/doc/recordproto/record.xml
# << files


